#!/usr/bin/python3
import sys
import math

with open(sys.argv[1], 'r') as file:
    lines = file.readlines()
    
    for line in lines:
        number = int(line)
        sq_rt = int(math.sqrt(number)) + 1
        factors = []
        for i in range(2, sq_rt):
            if number % i == 0:
                factors.append(i)
                factors.append(number // i)
                print(f"{number:d}={factors[1]:d}*{factors[0]:d}")
                break
        else:
            print(f"{number:d}={number:d}*{1:d}")

        