#!/usr/bin/python3
#!/usr/bin/python3
import sys

def factorize(number):
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return f"{number}={i}*{number//i}"
    return f"{number}={number}*1"

def main(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()

        for line in lines:
            number = int(line.strip())
            result = factorize(number)
            print(result)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    main(sys.argv[1])